import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";
import type { APIResponse } from "@/lib/constants";
import type { ColumnDef } from "@tanstack/react-table";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const scrollToBottom = () => {
  window.scrollTo({
    top: document.body.scrollHeight,
    behavior: "smooth",
  });
};

interface BackendColumnDef {
  header: string;
  accessorKey: string;
  sqlDataType: string;
  isNullable?: boolean;
  isPrimaryKey?: boolean;
  isAutoGenerated?: boolean;
  auditRole?: "created" | "updated" | null;
  isAutoManaged?: boolean;
}

export type TableColumnConfig = BackendColumnDef;

const isTimestampType = (sqlDataType: string): boolean =>
  sqlDataType === "timestamp with time zone" ||
  sqlDataType === "timestamp without time zone" ||
  sqlDataType === "date" ||
  sqlDataType.startsWith("timestamp");

export { isTimestampType };

export const isFormFieldVisible = (
  col: TableColumnConfig,
  mode: "add" | "edit"
): boolean => {
  if (mode === "add") {
    if (col.isAutoManaged) return false;
    if (col.isPrimaryKey && col.isAutoGenerated) return false;
  }
  return true;
};

export const isFormFieldReadonly = (
  col: TableColumnConfig,
  mode: "add" | "edit"
): boolean =>
  mode === "edit" && Boolean(col.isPrimaryKey || col.isAutoManaged);

export const toDatetimeLocal = (value: unknown): string => {
  if (!value) return "";
  const date = new Date(value as string);
  if (isNaN(date.getTime())) return "";
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;
};

export const parseFormFieldValue = (
  col: TableColumnConfig,
  value: unknown
): unknown => {
  if (col.sqlDataType === "boolean") return value;
  if (value === "" || value === undefined) return null;
  if (col.sqlDataType === "integer") return Number(value);
  if (col.sqlDataType.includes("numeric")) return Number(value);
  if (isTimestampType(col.sqlDataType))
    return new Date(value as string).toISOString();
  return value;
};

export const getInitialFormValue = (
  col: TableColumnConfig,
  record?: Record<string, unknown> | null
): unknown => {
  const raw = record?.[col.accessorKey];
  if (col.sqlDataType === "boolean") return Boolean(raw);
  if (isTimestampType(col.sqlDataType)) return toDatetimeLocal(raw);
  if (raw === null || raw === undefined) return "";
  return raw;
};

export const formatBackendColumnDefToFrontend = (
  data: APIResponse<ColumnDef<unknown>[]>
): APIResponse<ColumnDef<unknown>[]> => {
  if (!data.success) return data;
  if (!data?.data) return data;
  const backendColumns = data.data as BackendColumnDef[];
  return {
    ...data,
    data: backendColumns.map((col) => ({
      header: col.header,
      accessorKey: col.accessorKey,
      cell: (info) => {
        const value = info.getValue();
        if (isTimestampType(col.sqlDataType) && value) {
          const date = new Date(value as string);
          if (!isNaN(date.getTime())) {
            return date.toLocaleString();
          }
        }
        return value;
      },
    })),
  };
};
