import { Request, Response } from "express";
import * as dataModelService from "../services/dataModelService.js";
import { ApiResponse, ApiResponsePageable, TableConfigBasic } from "../lib/types.js";
import logger from "../config/logger.js";
import { keyToLabel } from "../lib/utils.js";
import { protectedDataModels } from "../lib/constants.js";

const handleError = (res: Response, error: unknown, message: string) => {
  logger.error(message, { error });
  const response: ApiResponse = {
    success: false,
    error: error instanceof Error ? error.message : "Unknown error",
  };
  res.status(500).json(response);
};

const isForbiddenTable = (tableName: string): boolean =>
  protectedDataModels.includes(tableName);

export const getListOfTables = async (
  req: Request,
  res: Response
): Promise<void> => {
  try {
    const tableList = await dataModelService.getAllTableSchemas();
    const filteredTables = tableList.reduce((acc, curr) => {
      if (!protectedDataModels.includes(curr.table_name))
        acc.push({
          label: keyToLabel(curr.table_name),
          value: curr.table_name,
        });
      return acc;
    }, []);
    const response: ApiResponse<any[]> = {
      success: true,
      data: filteredTables,
    };
    res.status(200).json(response);
  } catch (error) {
    handleError(res, error, "Error fetching database schema details:");
  }
};

export const getTableConfig = async (
  req: Request,
  res: Response
): Promise<void> => {
  try {
    const { tableName } = req.params;
    if (isForbiddenTable(tableName)) {
      res.status(403).json({
        success: false,
        error: "Access to this table is forbidden",
      });
      return;
    }
    const tableConfig: TableConfigBasic[] =
      await dataModelService.getTableConfig(tableName);
    if (!tableConfig || tableConfig.length === 0) {
      res.status(404).json({
        success: false,
        error: "Table configuration not found",
      });
      return;
    }
    const tanstackTableColumnDef = tableConfig.map((column) => ({
      accessorKey: column.column_name,
      header: keyToLabel(column.column_name),
      sqlDataType: column.data_type,
      isNullable: column.is_nullable === "YES",
      isPrimaryKey: column.is_primary_key ?? false,
      isAutoGenerated: column.is_auto_generated ?? false,
      auditRole: column.audit_role ?? null,
      isAutoManaged: column.is_auto_managed ?? false,
    }));
    const response: ApiResponse = {
      success: true,
      data: tanstackTableColumnDef,
    };
    res.status(200).json(response);
  } catch (error) {
    handleError(res, error, "Error fetching table configuration:");
  }
};

export const getTableData = async (
  req: Request,
  res: Response
): Promise<void> => {
  try {
    const { tableName } = req.params;
    const page = req.query.page;
    const pageNum = isNaN(Number(page)) ? 0 : Number(page);
    const sortBy =
      typeof req.query.sortBy === "string" ? req.query.sortBy : undefined;
    const sortDir: "asc" | "desc" | undefined =
      req.query.sortDir === "desc"
        ? "desc"
        : req.query.sortDir === "asc"
          ? "asc"
          : undefined;
    const search =
      typeof req.query.search === "string" ? req.query.search : undefined;
    if (isForbiddenTable(tableName)) {
      res.status(403).json({
        success: false,
        error: "Access to this table is forbidden",
      });
      return;
    }
    const queryOptions = { sortBy, sortDir, search };
    const p1 = dataModelService.getTableRowCount(tableName, search);
    const p2 = dataModelService.getTableData(tableName, pageNum, queryOptions);
    const result = Promise.all([p1, p2]);
    const [totalElements, tableData] = await result;
    const response: ApiResponsePageable = {
      success: true,
      data: {
        content: tableData,
        totalElements: +totalElements,
      },
    };
    res.status(200).json(response);
  } catch (error) {
    handleError(res, error, "Error fetching table data:");
  }
};

export const createRecord = async (
  req: Request,
  res: Response
): Promise<void> => {
  try {
    const { tableName } = req.params;
    if (isForbiddenTable(tableName)) {
      res.status(403).json({
        success: false,
        error: "Access to this table is forbidden",
      });
      return;
    }
    const row = await dataModelService.insertTableRecord(
      tableName,
      req.body as Record<string, unknown>
    );
    const response: ApiResponse = { success: true, data: row };
    res.status(201).json(response);
  } catch (error) {
    if (error instanceof Error && error.message === "Table not found") {
      res.status(404).json({ success: false, error: error.message });
      return;
    }
    handleError(res, error, "Error creating record:");
  }
};

export const updateRecord = async (
  req: Request,
  res: Response
): Promise<void> => {
  try {
    const { tableName, recordId } = req.params;
    if (isForbiddenTable(tableName)) {
      res.status(403).json({
        success: false,
        error: "Access to this table is forbidden",
      });
      return;
    }
    const row = await dataModelService.updateTableRecord(
      tableName,
      recordId,
      req.body as Record<string, unknown>
    );
    const response: ApiResponse = { success: true, data: row };
    res.status(200).json(response);
  } catch (error) {
    if (error instanceof Error && error.message === "Record not found") {
      res.status(404).json({ success: false, error: error.message });
      return;
    }
    if (error instanceof Error && error.message === "Table not found") {
      res.status(404).json({ success: false, error: error.message });
      return;
    }
    handleError(res, error, "Error updating record:");
  }
};

export const deleteRecord = async (
  req: Request,
  res: Response
): Promise<void> => {
  try {
    const { tableName, recordId } = req.params;
    if (isForbiddenTable(tableName)) {
      res.status(403).json({
        success: false,
        error: "Access to this table is forbidden",
      });
      return;
    }
    const row = await dataModelService.deleteTableRecord(tableName, recordId);
    const response: ApiResponse = { success: true, data: row };
    res.status(200).json(response);
  } catch (error) {
    if (error instanceof Error && error.message === "Record not found") {
      res.status(404).json({ success: false, error: error.message });
      return;
    }
    if (error instanceof Error && error.message === "Table not found") {
      res.status(404).json({ success: false, error: error.message });
      return;
    }
    handleError(res, error, "Error deleting record:");
  }
};
