import { query } from "../config/db.js";
import { protectedDataModels } from "../lib/constants.js";
import { AuditRole, TableConfigBasic } from "../lib/types.js";
import { multipleQueryHandler } from "../lib/utils.js";

const TIMESTAMP_TYPES = new Set([
  "timestamp with time zone",
  "timestamp without time zone",
  "date",
]);

const CREATED_NAME_RE = /created|inserted|added/i;
const UPDATED_NAME_RE = /updated|modified|changed/i;
const TRIGGER_NEW_COLUMN_RE = /NEW\.([a-zA-Z_][a-zA-Z0-9_]*)\s*=/g;

interface InformationSchemaColumnRow {
  column_name: string;
  data_type: string;
  is_nullable: string;
  column_default?: string | null;
  is_identity?: string;
}

interface TriggerProcRow {
  prosrc: string;
}

const isColumnAutoGenerated = (column: {
  is_identity?: string;
  column_default?: string | null;
}): boolean =>
  column.is_identity === "YES" ||
  (column.column_default?.startsWith("nextval(") ?? false);

const isTimestampType = (dataType: string): boolean =>
  TIMESTAMP_TYPES.has(dataType) || dataType.startsWith("timestamp");

const hasNowDefault = (columnDefault?: string | null): boolean => {
  if (!columnDefault) return false;
  const lower = columnDefault.toLowerCase();
  return lower.includes("now()") || lower.includes("current_timestamp");
};

const classifyAuditColumn = (
  column: {
    column_name: string;
    data_type: string;
    column_default?: string | null;
  },
  triggerManagedColumns: Set<string>
): { audit_role: AuditRole; is_auto_managed: boolean } => {
  const isTimestamp = isTimestampType(column.data_type);
  const isCreatedName = CREATED_NAME_RE.test(column.column_name);
  const isUpdatedName = UPDATED_NAME_RE.test(column.column_name);
  const triggerManaged = triggerManagedColumns.has(column.column_name);
  const hasNow = hasNowDefault(column.column_default);

  if (isTimestamp && triggerManaged) {
    return { audit_role: "updated", is_auto_managed: true };
  }

  if (isTimestamp && isCreatedName && hasNow) {
    return { audit_role: "created", is_auto_managed: true };
  }

  if (isTimestamp && isUpdatedName) {
    return { audit_role: "updated", is_auto_managed: true };
  }

  if (isTimestamp && hasNow && !isUpdatedName) {
    return { audit_role: "created", is_auto_managed: true };
  }

  return { audit_role: null, is_auto_managed: false };
};

const getTriggerManagedColumns = async (
  tableName: string
): Promise<Set<string>> => {
  const result = await query<TriggerProcRow>(
    `SELECT p.prosrc
     FROM pg_trigger t
     JOIN pg_class c ON c.oid = t.tgrelid
     JOIN pg_proc p ON p.oid = t.tgfoid
     WHERE c.relname = $1
       AND NOT t.tgisinternal
       AND (t.tgtype & 2) <> 0
       AND (t.tgtype & 16) <> 0`,
    [tableName]
  );

  const columns = new Set<string>();
  for (const row of multipleQueryHandler(result).rows) {
    const matches = row.prosrc.matchAll(TRIGGER_NEW_COLUMN_RE);
    for (const match of matches) {
      columns.add(match[1]);
    }
  }
  return columns;
};

export const assertTableAllowed = (tableName: string): void => {
  if (protectedDataModels.includes(tableName)) {
    throw new Error("Access to this table is forbidden");
  }
};

export const assertTableExists = async (tableName: string): Promise<void> => {
  const tables = await getAllTableSchemas();
  if (!tables.some((t) => t.table_name === tableName)) {
    throw new Error("Table not found");
  }
};

export const getAllTableSchemas = async (): Promise<any[]> => {
  try {
    const result = await query(`
      SELECT table_name
      FROM information_schema.tables
      WHERE table_type = 'BASE TABLE'
        AND table_schema NOT IN ('pg_catalog', 'information_schema')
    `);
    return multipleQueryHandler(result).rows;
  } catch (error) {
    throw new Error(
      `Failed to fetch table schemas: ${
        error instanceof Error ? error.message : "Unknown error"
      }`
    );
  }
};

export const getPrimaryKeyColumn = async (tableName: string): Promise<string> => {
  try {
    const pkResult = await query(
      `SELECT a.attname as column_name
       FROM pg_index i
       JOIN pg_attribute a ON a.attrelid = i.indrelid
                AND a.attnum = ANY(i.indkey)
       WHERE i.indrelid = $1::regclass
       AND i.indisprimary`,
      [tableName]
    );
    return multipleQueryHandler(pkResult).rows[0]?.column_name || "created_at";
  } catch (error) {
    throw new Error(
      `Failed to fetch primary key: ${
        error instanceof Error ? error.message : "Unknown error"
      }`
    );
  }
};

const getPrimaryKeyColumns = async (tableName: string): Promise<string[]> => {
  const pkResult = await query(
    `SELECT a.attname as column_name
     FROM pg_index i
     JOIN pg_attribute a ON a.attrelid = i.indrelid
              AND a.attnum = ANY(i.indkey)
     WHERE i.indrelid = $1::regclass
     AND i.indisprimary`,
    [tableName]
  );
  return multipleQueryHandler(pkResult).rows.map((row) => row.column_name);
};

export const getTableConfig = async (
  tableName: string
): Promise<TableConfigBasic[]> => {
  try {
    const pkColumns = await getPrimaryKeyColumns(tableName);
    const pkSet = new Set(pkColumns);
    const triggerManagedColumns = await getTriggerManagedColumns(tableName);

    const result = await query<InformationSchemaColumnRow>(
      `SELECT
        column_name,
        data_type,
        is_nullable,
        column_default,
        is_identity
      FROM information_schema.columns
      WHERE table_name = $1
      ORDER BY ordinal_position`,
      [tableName]
    );

    return multipleQueryHandler(result).rows.map((column) => {
      const audit = classifyAuditColumn(column, triggerManagedColumns);
      return {
        column_name: column.column_name,
        data_type: column.data_type,
        is_nullable: column.is_nullable,
        column_default: column.column_default,
        is_identity: column.is_identity,
        is_primary_key: pkSet.has(column.column_name),
        is_auto_generated: isColumnAutoGenerated(column),
        audit_role: audit.audit_role,
        is_auto_managed: audit.is_auto_managed,
      };
    });
  } catch (error) {
    throw new Error(
      `Failed to fetch table config: ${
        error instanceof Error ? error.message : "Unknown error"
      }`
    );
  }
};

const getInsertableKeys = (
  config: TableConfigBasic[],
  data: Record<string, unknown>
): string[] =>
  Object.keys(data).filter((key) => {
    const column = config.find((c) => c.column_name === key);
    if (!column) return false;
    if (column.is_auto_managed) return false;
    if (column.is_primary_key && column.is_auto_generated) return false;
    return true;
  });

const getUpdatableKeys = (
  config: TableConfigBasic[],
  data: Record<string, unknown>
): string[] =>
  Object.keys(data).filter((key) => {
    const column = config.find((c) => c.column_name === key);
    if (!column) return false;
    if (column.is_primary_key) return false;
    if (column.is_auto_managed) return false;
    return true;
  });

export const insertTableRecord = async (
  tableName: string,
  data: Record<string, unknown>
): Promise<Record<string, unknown>> => {
  assertTableAllowed(tableName);
  await assertTableExists(tableName);

  const config = await getTableConfig(tableName);
  const keys = getInsertableKeys(config, data);

  if (keys.length === 0) {
    throw new Error("No valid fields provided for insert");
  }

  const columns = keys.map((key) => `"${key}"`).join(", ");
  const placeholders = keys.map((_, i) => `$${i + 1}`).join(", ");
  const values = keys.map((key) => data[key]);

  const result = await query(
    `INSERT INTO ${tableName} (${columns}) VALUES (${placeholders}) RETURNING *`,
    values
  );

  return multipleQueryHandler(result).rows[0];
};

export const updateTableRecord = async (
  tableName: string,
  recordId: string,
  data: Record<string, unknown>
): Promise<Record<string, unknown>> => {
  assertTableAllowed(tableName);
  await assertTableExists(tableName);

  const config = await getTableConfig(tableName);
  const keys = getUpdatableKeys(config, data);

  if (keys.length === 0) {
    throw new Error("No valid fields provided for update");
  }

  const pkColumn = await getPrimaryKeyColumn(tableName);
  const setClause = keys
    .map((key, i) => `"${key}" = $${i + 1}`)
    .join(", ");
  const values = keys.map((key) => data[key]);
  values.push(recordId);

  const result = await query(
    `UPDATE ${tableName} SET ${setClause} WHERE "${pkColumn}" = $${keys.length + 1} RETURNING *`,
    values
  );

  const row = multipleQueryHandler(result).rows[0];
  if (!row) {
    throw new Error("Record not found");
  }
  return row;
};

export const deleteTableRecord = async (
  tableName: string,
  recordId: string
): Promise<Record<string, unknown>> => {
  assertTableAllowed(tableName);
  await assertTableExists(tableName);

  const pkColumn = await getPrimaryKeyColumn(tableName);
  const result = await query(
    `DELETE FROM ${tableName} WHERE "${pkColumn}" = $1 RETURNING *`,
    [recordId]
  );

  const row = multipleQueryHandler(result).rows[0];
  if (!row) {
    throw new Error("Record not found");
  }
  return row;
};

export const getTableData = async (
  tableName: string,
  page: number
): Promise<any[]> => {
  try {
    const PAGE_SIZE = 10;
    const pkColumn = await getPrimaryKeyColumn(tableName);

    const result = await query(
      `SELECT *
      FROM ${tableName}
      ORDER BY "${pkColumn}"
      LIMIT $1 OFFSET $2`,
      [PAGE_SIZE, page * PAGE_SIZE]
    );
    return multipleQueryHandler(result).rows;
  } catch (error) {
    throw new Error(
      `Failed to fetch table data: ${
        error instanceof Error ? error.message : "Unknown error"
      }`
    );
  }
};

export const getTableRowCount = async (tableName: string): Promise<number> => {
  try {
    const result = await query(
      `SELECT COUNT(*) as count
      FROM ${tableName}`
    );
    return multipleQueryHandler(result).rows[0].count;
  } catch (error) {
    throw new Error(
      `Failed to fetch table row count: ${
        error instanceof Error ? error.message : "Unknown error"
      }`
    );
  }
};
